alias g='git'
alias ga='git a'
alias gaa='git aa'
alias gb='git b'
alias gbd='git bd'
alias gbdr='git bdr'
alias gbn='git bn'
alias gc='git c'
alias gca='git ca'
alias gcam='git cam'
alias gcm='git cm'
alias gco='git co'
alias gcp='git cp'
alias gd='git d'
alias gdc='git dc'
alias glds='git lds'
alias gll='git ll'
alias gls='git ls'
alias gm='git m'
alias gpl='git pull'
alias gpc='git push --set-upstream origin "$(git-branch-current 2> /dev/null)"'
alias gps='git push'
alias gr='git r'
alias gs='git s'
alias gsh='git show'
alias gt='git tag -l -n1 | sort -V'
alias gtn='git tn'

alias ap='pwd; echo "Continue?"; read; ansible-playbook --vault-password-file=~/.vault_pass.txt -i inventory'

alias backup-home='rsync -ah --progress --stats --delete /home/ckoehn/ /run/media/ckoehn/Master/home/'
alias sync-backup='rsync -ah --progress --stats --delete /run/media/ckoehn/Master/ /run/media/ckoehn/Slave/'
